// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dropcrate/v1/dropcrate.proto

package dropcratev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FileInfo is the metadata dropcrate tracks for a stored file.
type FileInfo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename    string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size        int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// expires_at is unset when the file never expires.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_dropcrate_v1_dropcrate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dropcrate_v1_dropcrate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_dropcrate_v1_dropcrate_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FileInfo) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// UploadInfo is the header sent as the first Upload message.
type UploadInfo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Filename    string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// ttl_seconds controls the file's lifetime:
	//
	//	0        -> use the server default TTL
	//	negative -> never expire
	//	positive -> expire this many seconds after creation
	TtlSeconds    int64 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadInfo) Reset() {
	*x = UploadInfo{}
	mi := &file_dropcrate_v1_dropcrate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadInfo) ProtoMessage() {}

func (x *UploadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dropcrate_v1_dropcrate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadInfo.ProtoReflect.Descriptor instead.
func (*UploadInfo) Descriptor() ([]byte, []int) {
	return file_dropcrate_v1_dropcrate_proto_rawDescGZIP(), []int{1}
}

func (x *UploadInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadInfo) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadRequest_Info
	//	*UploadRequest_Chunk
	Payload       isUploadRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_dropcrate_v1_dropcrate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dropcrate_v1_dropcrate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_dropcrate_v1_dropcrate_proto_rawDescGZIP(), []int{2}
}

func (x *UploadRequest) GetPayload() isUploadRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadRequest) GetInfo() *UploadInfo {
	if x != nil {
		if x, ok := x.Payload.(*UploadRequest_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *UploadRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*UploadRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadRequest_Payload interface {
	isUploadRequest_Payload()
}

type UploadRequest_Info struct {
	Info *UploadInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"` // first message only
}

type UploadRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // subsequent messages
}

func (*UploadRequest_Info) isUploadRequest_Payload() {}

func (*UploadRequest_Chunk) isUploadRequest_Payload() {}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_dropcrate_v1_dropcrate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dropcrate_v1_dropcrate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_dropcrate_v1_dropcrate_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DownloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DownloadResponse_Info
	//	*DownloadResponse_Chunk
	Payload       isDownloadResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_dropcrate_v1_dropcrate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dropcrate_v1_dropcrate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_dropcrate_v1_dropcrate_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadResponse) GetPayload() isDownloadResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DownloadResponse) GetInfo() *FileInfo {
	if x != nil {
		if x, ok := x.Payload.(*DownloadResponse_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *DownloadResponse) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*DownloadResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isDownloadResponse_Payload interface {
	isDownloadResponse_Payload()
}

type DownloadResponse_Info struct {
	Info *FileInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"` // first message only
}

type DownloadResponse_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // subsequent messages
}

func (*DownloadResponse_Info) isDownloadResponse_Payload() {}

func (*DownloadResponse_Chunk) isDownloadResponse_Payload() {}

type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_dropcrate_v1_dropcrate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dropcrate_v1_dropcrate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_dropcrate_v1_dropcrate_proto_rawDescGZIP(), []int{5}
}

func (x *GetMetadataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_dropcrate_v1_dropcrate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dropcrate_v1_dropcrate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_dropcrate_v1_dropcrate_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_dropcrate_v1_dropcrate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dropcrate_v1_dropcrate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_dropcrate_v1_dropcrate_proto_rawDescGZIP(), []int{7}
}

var File_dropcrate_v1_dropcrate_proto protoreflect.FileDescriptor

const file_dropcrate_v1_dropcrate_proto_rawDesc = "" +
	"\n" +
	"\x1cdropcrate/v1/dropcrate.proto\x12\fdropcrate.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x01\n" +
	"\bFileInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"l\n" +
	"\n" +
	"UploadInfo\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"b\n" +
	"\rUploadRequest\x12.\n" +
	"\x04info\x18\x01 \x01(\v2\x18.dropcrate.v1.UploadInfoH\x00R\x04info\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"!\n" +
	"\x0fDownloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"c\n" +
	"\x10DownloadResponse\x12,\n" +
	"\x04info\x18\x01 \x01(\v2\x16.dropcrate.v1.FileInfoH\x00R\x04info\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"$\n" +
	"\x12GetMetadataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x10\n" +
	"\x0eDeleteResponse2\xa9\x02\n" +
	"\vFileService\x12?\n" +
	"\x06Upload\x12\x1b.dropcrate.v1.UploadRequest\x1a\x16.dropcrate.v1.FileInfo(\x01\x12K\n" +
	"\bDownload\x12\x1d.dropcrate.v1.DownloadRequest\x1a\x1e.dropcrate.v1.DownloadResponse0\x01\x12G\n" +
	"\vGetMetadata\x12 .dropcrate.v1.GetMetadataRequest\x1a\x16.dropcrate.v1.FileInfo\x12C\n" +
	"\x06Delete\x12\x1b.dropcrate.v1.DeleteRequest\x1a\x1c.dropcrate.v1.DeleteResponseBEZCgithub.com/IgliHoxha/dropcrate/internal/rpc/dropcratev1;dropcratev1b\x06proto3"

var (
	file_dropcrate_v1_dropcrate_proto_rawDescOnce sync.Once
	file_dropcrate_v1_dropcrate_proto_rawDescData []byte
)

func file_dropcrate_v1_dropcrate_proto_rawDescGZIP() []byte {
	file_dropcrate_v1_dropcrate_proto_rawDescOnce.Do(func() {
		file_dropcrate_v1_dropcrate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dropcrate_v1_dropcrate_proto_rawDesc), len(file_dropcrate_v1_dropcrate_proto_rawDesc)))
	})
	return file_dropcrate_v1_dropcrate_proto_rawDescData
}

var file_dropcrate_v1_dropcrate_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_dropcrate_v1_dropcrate_proto_goTypes = []any{
	(*FileInfo)(nil),              // 0: dropcrate.v1.FileInfo
	(*UploadInfo)(nil),            // 1: dropcrate.v1.UploadInfo
	(*UploadRequest)(nil),         // 2: dropcrate.v1.UploadRequest
	(*DownloadRequest)(nil),       // 3: dropcrate.v1.DownloadRequest
	(*DownloadResponse)(nil),      // 4: dropcrate.v1.DownloadResponse
	(*GetMetadataRequest)(nil),    // 5: dropcrate.v1.GetMetadataRequest
	(*DeleteRequest)(nil),         // 6: dropcrate.v1.DeleteRequest
	(*DeleteResponse)(nil),        // 7: dropcrate.v1.DeleteResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_dropcrate_v1_dropcrate_proto_depIdxs = []int32{
	8, // 0: dropcrate.v1.FileInfo.created_at:type_name -> google.protobuf.Timestamp
	8, // 1: dropcrate.v1.FileInfo.expires_at:type_name -> google.protobuf.Timestamp
	1, // 2: dropcrate.v1.UploadRequest.info:type_name -> dropcrate.v1.UploadInfo
	0, // 3: dropcrate.v1.DownloadResponse.info:type_name -> dropcrate.v1.FileInfo
	2, // 4: dropcrate.v1.FileService.Upload:input_type -> dropcrate.v1.UploadRequest
	3, // 5: dropcrate.v1.FileService.Download:input_type -> dropcrate.v1.DownloadRequest
	5, // 6: dropcrate.v1.FileService.GetMetadata:input_type -> dropcrate.v1.GetMetadataRequest
	6, // 7: dropcrate.v1.FileService.Delete:input_type -> dropcrate.v1.DeleteRequest
	0, // 8: dropcrate.v1.FileService.Upload:output_type -> dropcrate.v1.FileInfo
	4, // 9: dropcrate.v1.FileService.Download:output_type -> dropcrate.v1.DownloadResponse
	0, // 10: dropcrate.v1.FileService.GetMetadata:output_type -> dropcrate.v1.FileInfo
	7, // 11: dropcrate.v1.FileService.Delete:output_type -> dropcrate.v1.DeleteResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dropcrate_v1_dropcrate_proto_init() }
func file_dropcrate_v1_dropcrate_proto_init() {
	if File_dropcrate_v1_dropcrate_proto != nil {
		return
	}
	file_dropcrate_v1_dropcrate_proto_msgTypes[2].OneofWrappers = []any{
		(*UploadRequest_Info)(nil),
		(*UploadRequest_Chunk)(nil),
	}
	file_dropcrate_v1_dropcrate_proto_msgTypes[4].OneofWrappers = []any{
		(*DownloadResponse_Info)(nil),
		(*DownloadResponse_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dropcrate_v1_dropcrate_proto_rawDesc), len(file_dropcrate_v1_dropcrate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dropcrate_v1_dropcrate_proto_goTypes,
		DependencyIndexes: file_dropcrate_v1_dropcrate_proto_depIdxs,
		MessageInfos:      file_dropcrate_v1_dropcrate_proto_msgTypes,
	}.Build()
	File_dropcrate_v1_dropcrate_proto = out.File
	file_dropcrate_v1_dropcrate_proto_goTypes = nil
	file_dropcrate_v1_dropcrate_proto_depIdxs = nil
}
